apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port | default 3111 }} 
    protocol: {{ .Values.service.protocol }} 
    targetPort: {{ if .Values.service.targetPort }}
                {{ .Values.service.targetPort }}
                {{ else }}
                {{ .Values.service.port | default 3111 }}
                {{ end }}
  type: {{ .Values.service.type }} 
